spring:
  application:
      name : backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/lionphago
knife4j:
  enable: false
  setting:
    language: zh_cn